name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
 MONGODB_URL: ${{ secrets.MONGODB_URL }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t emp .
    - name: Tag the docker image
      run: docker tag emp nanikreddy/node-hello-world
    - name: docker login 
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -P ${{ secrets.DOCKER-PASSWORD }}
    - name: docker push
      run: docker push nanikreddy/node-hello-world

