name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t emp .
    - name: Tag the docker image
      run: docker tag emp sameerdevops71814329/test:tagname
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker image
      run: docker push sameerdevops71814329/test:tagname 
